FROM oven/bun:1 AS builder
WORKDIR /app

COPY package.json ./
COPY bun.lock* bun.lockb* ./
RUN bun install

COPY . .
RUN bun run build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html

COPY --from=builder /app/dist ./

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
